name: Publish to jsr (Release Published)

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Get deno version
        id: deno-version
        run: echo deno-version=`cat .tool-versions | grep deno | sed -e "s/deno //"` >> $GITHUB_OUTPUT
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v${{ steps.deno-version.outputs.deno-version }}
      - run: deno publish
