name: Publish to jsr (Release Published)

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Get deno version
        id: deno-version
        run: echo deno-version=`cat .tool-versions | grep deno | sed -e "s/deno //"` >> $GITHUB_OUTPUT
      - uses: denoland/setup-deno@11b63cf76cfcafb4e43f97b6cad24d8e8438f62d # v1.5.2
        with:
          deno-version: v${{ steps.deno-version.outputs.deno-version }}
      - run: deno publish
