name: Validate Biome Schema (Pull Request)

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version-file: .tool-versions
          cache: true
      - name: Check validation script
        run: deno check validate-schema.ts
      - name: Validate schema
        run: deno run --allow-net validate-schema.ts
